#!/usr/bin/env python3
"""
wsCmd.py — MultiTaskWS platform management.

Run from the pyMultiTaskWS/ directory.

Setup (first time or reset):
    python3 wsCmd.py --setup
    python3 wsCmd.py --setup --reset

Start locally (full WSGI dispatcher with all mounted Trackers):
    python3 wsCmd.py --start
    python3 wsCmd.py --start --local --port 8080

Start in WSGI mode (full dispatcher, mirrors PA environment):
    python3 wsCmd.py --start --wsgi

PythonAnywhere: wsgi.py imports make_application() — no CLI args needed.

Config: ~/.MultiTaskWS/MultiTaskWS_config.json
  Top-level fields (stored for recovery; not used by any Tracker directly):
    WEB_GPG_PASSPHRASE         — master passphrase; tracker passphrases derived from it
    WEB_SECRET_KEY             — platform-level key (not used by trackers)
    WebServer                  — 'Host_<pa-user>' or 'local_<machine>'
    Trackers                   — list of Tracker entries

  Per-tracker stanza (keyed by stanza_key, e.g. "adminTracker"):
    APP_GPG_PASSPHRASE         — derived as <top>_<stanza_key>
    WEB_SECRET_KEY             — tracker-specific random key
    (external trackers use their own env var names, e.g. LLC_GPG_PASSPHRASE)
"""

import argparse
import getpass
import importlib.util
import json
import os
import platform
import secrets
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Anchor pyMultiTaskWS/ on sys.path so multitrack.* and adminTracker.* are importable.
_here = Path(__file__).resolve().parent
if str(_here) not in sys.path:
    sys.path.insert(0, str(_here))

from multitrack.auth import find_user, hash_password, load_users, save_users

# ── Constants ─────────────────────────────────────────────────────────────────

DEPS = ["flask", "werkzeug"]

_ADMIN_DB  = _here / "adminTracker" / "Accts" / "pw.json.gpg"
_ADMIN_ID  = "wbgadminWS"

_SEED_USER = {
    "username":   "webadmin",
    "password":   hash_password("WebAdmin0!"),
    "full_name":  "WBGroup Admin",
    "phone":      "",
    "role":       "member",
    "created_at": "2026-01-01T00:00:00",
}

# stanza_key is the key under which this tracker's credentials are stored in the config.
# Passphrase formula: <top_passphrase>_<stanza_key>
_DEFAULT_TRACKERS = [
    {
        "name":        "AdminTracker",
        "mount":       "/admin",
        "url":         "/admin/",
        "description": "Platform administration — user management & tracker index",
        "status":      "online",
        "builtin":     True,
        "stanza_key":  "adminTracker",
    }
]

# Keys stripped from Tracker entries before they are shown in the registry / home page.
_INTERNAL_KEYS = {"builtin", "sys_path", "stanza_key"}


# ── WsCmd class ───────────────────────────────────────────────────────────────

class WsCmd:
    """
    MultiTaskWS platform manager.

    Config: ~/.MultiTaskWS/MultiTaskWS_config.json (chmod 600)
    Top-level keys store the master passphrase for recovery only.
    Each Tracker has its own stanza keyed by stanza_key:
      {
        "APP_GPG_PASSPHRASE": "<top>_<stanza_key>",
        "WEB_SECRET_KEY": "<tracker-specific-random>"
      }
    External trackers use their own env var names (e.g. LLC_GPG_PASSPHRASE).
    """

    CONFIG_DIR  = Path.home() / ".MultiTaskWS"
    CONFIG_PATH = CONFIG_DIR  / "config.json"
    _LEGACY_PATH = CONFIG_DIR / "MultiTaskWS_config.json"

    def __init__(self):
        pass

    # ── helpers ───────────────────────────────────────────────────────────────

    def _load_config(self) -> dict:
        # Auto-migrate legacy filename on first access
        if not self.CONFIG_PATH.exists() and self._LEGACY_PATH.exists():
            self._LEGACY_PATH.rename(self.CONFIG_PATH)
            print(f"  ℹ  Migrated {self._LEGACY_PATH.name} → {self.CONFIG_PATH.name}")
        if not self.CONFIG_PATH.exists():
            return {}
        return json.loads(self.CONFIG_PATH.read_text(encoding="utf-8"))

    def _save_config(self, cfg: dict) -> None:
        self.CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        self.CONFIG_PATH.write_text(
            json.dumps(cfg, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        self.CONFIG_PATH.chmod(0o600)

    def _webserver_tag(self) -> str:
        home = Path.home()
        if str(home).startswith("/home/"):
            return f"Host_{home.name}"
        return f"local_{platform.node()}"

    # ── setup steps ───────────────────────────────────────────────────────────

    def _reset_config(self) -> None:
        print("\n── Step 0: Reset Configuration ─────────────────────────────────")
        # config.json is always deleted — it is fully regenerated by --setup.
        if self.CONFIG_PATH.exists():
            self.CONFIG_PATH.unlink()
            print(f"  ✓ Deleted {self.CONFIG_PATH.name}")
        elif self._LEGACY_PATH.exists():
            self._LEGACY_PATH.unlink()
            print(f"  ✓ Deleted {self._LEGACY_PATH.name}")
        else:
            print("  No existing config found — starting fresh.")

        # adminTracker DB is optional — ask separately, continue either way.
        if _ADMIN_DB.exists():
            ans = input(f"  Delete adminTracker user DB ({_ADMIN_DB.name})? [yes/NO]: ").strip().lower()
            if ans == "yes":
                _ADMIN_DB.unlink()
                print(f"  ✓ Deleted {_ADMIN_DB.name}")
            else:
                print(f"  Keeping {_ADMIN_DB.name} — setup will continue.")
                print(f"  Tip: to preserve pw.json.gpg, run setup WITHOUT --reset.")

    def _prompt_passphrase(self) -> str:
        print("\n── Step 1: Master GPG Passphrase ───────────────────────────────")
        print("Each Tracker's passphrase is derived as <master>_<trackerName>.")
        print("Only this master value is prompted — tracker values are generated.\n")
        while True:
            pp = getpass.getpass("  Enter master passphrase (min 12 chars): ").strip()
            if len(pp) < 12:
                print("  ✗ Too short — at least 12 characters required.")
                continue
            if getpass.getpass("  Confirm passphrase: ").strip() != pp:
                print("  ✗ Passphrases do not match.")
                continue
            break
        print("  ✓ Passphrase accepted.")
        return pp

    def _install_deps(self) -> None:
        print("\n── Step 2: Install Dependencies ────────────────────────────────")
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "--user", "--quiet"] + DEPS
        )
        if result.returncode != 0:
            print(f"  ✗ pip install failed. Run manually:")
            print(f"    pip install --user {' '.join(DEPS)}")
        else:
            print(f"  ✓ {', '.join(DEPS)} ready.")

    def _write_config(self, top_passphrase: str) -> None:
        """
        Write platform config and generate per-tracker stanzas.

        Top-level fields store the master passphrase for recovery only.
        Each builtin Tracker gets a stanza: { APP_GPG_PASSPHRASE, WEB_SECRET_KEY }
          passphrase = <top_passphrase>_<stanza_key>
          secret_key = new random hex (preserved across re-runs unless --reset)
        External trackers write their own stanza via their wsCmd.py --setup.
        """
        print("\n── Step 3: Write Platform Config ───────────────────────────────")
        cfg = self._load_config()

        # Top-level — stored for recovery; not injected into any Tracker.
        cfg["WEB_GPG_PASSPHRASE"] = top_passphrase
        cfg["WEB_SECRET_KEY"]            = secrets.token_hex(32)
        cfg["WebServer"]                 = self._webserver_tag()
        cfg.setdefault("Trackers", list(_DEFAULT_TRACKERS))

        # Generate stanzas for builtin Trackers.
        for t in cfg["Trackers"]:
            if not t.get("builtin"):
                continue
            sk          = t["stanza_key"]
            tracker_pp  = f"{top_passphrase}_{sk}"
            existing_sk = cfg.get(sk, {}).get("WEB_SECRET_KEY")
            cfg[sk] = {
                "APP_GPG_PASSPHRASE": tracker_pp,
                "WEB_SECRET_KEY":            existing_sk or secrets.token_hex(32),
            }
            print(f"    [{sk}] APP_GPG_PASSPHRASE         : {'*' * len(tracker_pp)}")
            print(f"    [{sk}] WEB_SECRET_KEY            : {cfg[sk]['WEB_SECRET_KEY'][:16]}…")

        self._save_config(cfg)
        print(f"  ✓ Saved → {self.CONFIG_PATH}  (chmod 600)")
        print(f"    WebServer : {cfg['WebServer']}")

    def _seed_admin_db(self) -> None:
        """Seed adminTracker/Accts/pw.json.gpg using the adminTracker stanza passphrase."""
        print("\n── Step 4: AdminTracker User Database ──────────────────────────")
        cfg          = self._load_config()
        admin_stanza = cfg.get("adminTracker", {})
        pp           = admin_stanza.get("APP_GPG_PASSPHRASE", "")
        if not pp:
            print("  ✗ adminTracker stanza not found in config — run --setup again.")
            sys.exit(1)

        # Set env var so multitrack.auth GPG operations use the tracker passphrase.
        os.environ["APP_GPG_PASSPHRASE"] = pp

        _ADMIN_DB.parent.mkdir(parents=True, exist_ok=True)
        users = []
        if _ADMIN_DB.exists():
            try:
                users = load_users(_ADMIN_DB)
                print(f"  Found existing DB ({len(users)} user(s)).")
            except Exception as exc:
                print(f"  ✗ Could not read existing DB: {exc}")
                print("    Starting fresh.")

        if not find_user(users, "webadmin"):
            users.append(_SEED_USER)
            print("  + Added seed user: webadmin / WebAdmin0!")
        else:
            print("  ✓ webadmin already present.")

        admin = find_user(users, _ADMIN_ID)
        if admin:
            admin["notes"] = f"Config stanza: adminTracker in {self.CONFIG_PATH}"
            print(f"  Updated {_ADMIN_ID} notes.")
        else:
            users.append({
                "username":   _ADMIN_ID,
                "password":   "",
                "full_name":  "webserver admin",
                "phone":      "",
                "role":       "member",
                "notes":      f"Config stanza: adminTracker in {self.CONFIG_PATH}",
                "created_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            })
            print(f"  + Created {_ADMIN_ID} record.")

        save_users(_ADMIN_DB, users)
        print(f"  ✓ Saved → {_ADMIN_DB}")

    # ── application builder ───────────────────────────────────────────────────

    def make_application(self):
        """
        Build and return the WSGI DispatcherMiddleware application.

        For each Tracker in config["Trackers"]:
          1. Read config[stanza_key] → set env vars (tracker-specific credentials).
          2. For builtin Trackers: import directly.
          3. For external Trackers: add sys_path, load wsgi.py via importlib.
        Returns the fully wired DispatcherMiddleware.
        """
        cfg      = self._load_config()
        trackers = cfg.get("Trackers", _DEFAULT_TRACKERS)

        # Registry: strip internal-only keys before the home page sees them.
        import adminTracker.registry as _reg
        _reg.TRACKERS = [
            {k: v for k, v in t.items() if k not in _INTERNAL_KEYS}
            for t in trackers
        ]

        # adminTracker — inject its stanza env vars, then import.
        for env_key, env_val in cfg.get("adminTracker", {}).items():
            os.environ[env_key] = env_val

        from adminTracker.wsgi import application as admin_app
        mounts = {"/admin": admin_app}

        # External Trackers — stanza provides env vars; Tracker entry provides sys_path.
        for t in trackers:
            if t.get("builtin"):
                continue
            stanza_key = t.get("stanza_key", t["mount"].strip("/"))
            for env_key, env_val in cfg.get(stanza_key, {}).items():
                os.environ[env_key] = env_val

            sys_path  = t.get("sys_path", "")
            wsgi_file = Path(sys_path) / "wsgi.py" if sys_path else None

            if sys_path and sys_path not in sys.path:
                sys.path.insert(0, sys_path)

            if not wsgi_file or not wsgi_file.exists():
                print(f"  ✗ {t['name']}: wsgi.py not found at {wsgi_file}")
                continue
            try:
                spec = importlib.util.spec_from_file_location(
                    f"tracker_{stanza_key}_wsgi", str(wsgi_file)
                )
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)
                mounts[t["mount"]] = mod.application
                print(f"  ✓ Mounted {t['name']} at {t['mount']}")
            except Exception as exc:
                print(f"  ✗ {t['name']}: failed to import wsgi.py — {exc}")

        from werkzeug.middleware.dispatcher import DispatcherMiddleware
        from werkzeug.exceptions import NotFound
        return DispatcherMiddleware(NotFound(), mounts)

    # ── public commands ───────────────────────────────────────────────────────

    def setup(self, reset: bool = False) -> None:
        """
        Interactive platform setup — writes ~/.MultiTaskWS/MultiTaskWS_config.json.

        Step 1: Prompt master passphrase.
        Step 2: Install Flask + Werkzeug.
        Step 3: Write config — derive per-tracker stanzas (<top>_<stanza_key>).
        Step 4: Seed adminTracker user DB using its stanza passphrase.
        """
        print()
        print("=" * 64)
        print("  MultiTaskWS — Platform Setup")
        print("=" * 64)

        if reset:
            self._reset_config()

        top_passphrase = self._prompt_passphrase()
        self._install_deps()
        self._write_config(top_passphrase)   # must run before _seed_admin_db
        self._seed_admin_db()                # reads adminTracker stanza from config

        print()
        print("=" * 64)
        print("  Setup complete.")
        print(f"  Config : {self.CONFIG_PATH}")
        print()
        print("  Recover master passphrase any time:")
        print(f"    python3 -c \"import json; c=json.load(open('{self.CONFIG_PATH}')); print(c['WEB_GPG_PASSPHRASE'])\"")
        print()
        print("  Start locally (full WSGI dispatcher):")
        print("    python3 wsCmd.py --start")
        print()
        print("  On PythonAnywhere:")
        print("    → Point WSGI config file to: wsgi.py")
        print("    → Hit Reload in the Web tab")
        print("    → Visit /admin/login  (webadmin / WebAdmin0!)")
        print("=" * 64)
        print()

    def start(self, wsgi_mode: bool = False,
              addr: str = "127.0.0.1", port: int = None,
              debug: bool = False) -> None:
        """
        Start the full WSGI dispatcher.

        --start (default / --local): Werkzeug dev server, port 8080.
        --start --wsgi: same dispatcher, no reloader (mirrors PA behavior).
        """
        _port = port or 8080

        print()
        print("=" * 64)
        label = "WSGI Start" if wsgi_mode else "Local Start"
        print(f"  MultiTaskWS — {label}  (http://{addr}:{_port})")
        print("=" * 64)

        application = self.make_application()

        cfg      = self._load_config()
        trackers = cfg.get("Trackers", _DEFAULT_TRACKERS)
        for t in trackers:
            print(f"  {t['mount']:10s} → {t['name']}")

        print()
        if wsgi_mode:
            print("  [WSGI mode] No reloader or debugger.")
        else:
            print(f"  Visit: http://127.0.0.1:{_port}/admin/login  (webadmin / WebAdmin0!)")

        from werkzeug.serving import run_simple
        run_simple(
            addr, _port, application,
            use_reloader=debug and not wsgi_mode,
            use_debugger=debug and not wsgi_mode,
        )


# ── CLI ───────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="wsCmd",
        description="MultiTaskWS platform management",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  python3 wsCmd.py --setup
  python3 wsCmd.py --setup --reset
  python3 wsCmd.py --start
  python3 wsCmd.py --start --wsgi
  python3 wsCmd.py --start --port 8080 --debug
""",
    )

    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--setup", action="store_true",
                      help="Interactive platform setup (writes ~/.MultiTaskWS/MultiTaskWS_config.json)")
    mode.add_argument("--start", action="store_true",
                      help="Start the full WSGI dispatcher")

    ap.add_argument("--reset", action="store_true",
                    help="[--setup] Delete config + adminTracker DB before setup")
    ap.add_argument("--local", action="store_true",
                    help="[--start] Local Werkzeug dev server (default)")
    ap.add_argument("--wsgi", action="store_true",
                    help="[--start] WSGI mode: no reloader/debugger (mirrors PA stack)")
    ap.add_argument("--addr", default="127.0.0.1", metavar="IP",
                    help="[--start] Bind address (default: 127.0.0.1)")
    ap.add_argument("--port", type=int, default=None,
                    help="[--start] Port (default: 8080)")
    ap.add_argument("--debug", action="store_true",
                    help="[--start] Enable reloader + debugger (ignored in --wsgi mode)")

    return ap


def main():
    args = _build_parser().parse_args()
    ws   = WsCmd()

    if args.setup:
        ws.setup(reset=args.reset)
    else:
        ws.start(
            wsgi_mode=args.wsgi,
            addr=args.addr,
            port=args.port,
            debug=args.debug,
        )


if __name__ == "__main__":
    main()
